package stock;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
/**
 *
 * @author indrajteotia
 */
public class B_Login extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    int n = 0;

    /**
     * Creates new form A_welcome
     */
    public B_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPnl = new javax.swing.JPanel();
        headLbl = new javax.swing.JLabel();
        admBtn = new javax.swing.JButton();
        usrBtn = new javax.swing.JButton();
        gstBtn = new javax.swing.JButton();
        idLbl = new javax.swing.JLabel();
        idLbl.setVisible(false);
        pwdLbl = new javax.swing.JLabel();
        pwdLbl.setVisible(false);
        idTxt = new javax.swing.JTextField();
        idTxt.setVisible(false);
        shwBtn = new javax.swing.JToggleButton();
        shwBtn.setVisible(false);
        loginBtn = new javax.swing.JButton();
        pwdTxt = new javax.swing.JPasswordField();
        pwdTxt.setVisible(false);
        pwdTxt.setEchoChar((char)0);
        icon = new javax.swing.JLabel();
        icon.setVisible(false);
        backBtn = new javax.swing.JButton();
        crtBtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Page");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 51));

        bodyPnl.setBackground(new java.awt.Color(0, 51, 51));
        bodyPnl.setLayout(null);

        headLbl.setFont(new java.awt.Font("Liberation Mono", 1, 36)); // NOI18N
        headLbl.setForeground(new java.awt.Color(0, 204, 204));
        headLbl.setText("Login Page");
        bodyPnl.add(headLbl);
        headLbl.setBounds(290, 20, 210, 70);

        admBtn.setBackground(new java.awt.Color(0, 102, 102));
        admBtn.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        admBtn.setForeground(new java.awt.Color(51, 204, 255));
        admBtn.setText("Admin");
        admBtn.setToolTipText("");
        admBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admBtn.setFocusPainted(false);
        admBtn.setRequestFocusEnabled(false);
        admBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                admBtnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                admBtnFocusLost(evt);
            }
        });
        admBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(admBtn);
        admBtn.setBounds(70, 160, 160, 50);

        usrBtn.setBackground(new java.awt.Color(0, 102, 102));
        usrBtn.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        usrBtn.setForeground(new java.awt.Color(51, 204, 255));
        usrBtn.setText("User");
        usrBtn.setToolTipText("");
        usrBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        usrBtn.setRequestFocusEnabled(false);
        usrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(usrBtn);
        usrBtn.setBounds(330, 160, 160, 50);

        gstBtn.setBackground(new java.awt.Color(0, 102, 102));
        gstBtn.setFont(new java.awt.Font("Snap ITC", 1, 36)); // NOI18N
        gstBtn.setForeground(new java.awt.Color(51, 204, 255));
        gstBtn.setText("Guest");
        gstBtn.setToolTipText("");
        gstBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gstBtn.setFocusPainted(false);
        gstBtn.setRequestFocusEnabled(false);
        gstBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gstBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(gstBtn);
        gstBtn.setBounds(580, 160, 160, 50);

        idLbl.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        idLbl.setForeground(new java.awt.Color(255, 153, 153));
        idLbl.setText("Id : ");
        bodyPnl.add(idLbl);
        idLbl.setBounds(170, 230, 60, 50);

        pwdLbl.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        pwdLbl.setForeground(new java.awt.Color(255, 153, 153));
        pwdLbl.setText("Password :");
        bodyPnl.add(pwdLbl);
        pwdLbl.setBounds(80, 270, 150, 50);

        idTxt.setBackground(new java.awt.Color(102, 255, 102));
        idTxt.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        idTxt.setForeground(new java.awt.Color(102, 0, 0));
        idTxt.setText("enter your id");
        idTxt.setToolTipText("enter your id");
        idTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        idTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idTxtMouseClicked(evt);
            }
        });
        bodyPnl.add(idTxt);
        idTxt.setBounds(240, 230, 350, 40);

        shwBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgShow.png"))); // NOI18N
        shwBtn.setBorder(null);
        shwBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shwBtnStateChanged(evt);
            }
        });
        shwBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shwBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(shwBtn);
        shwBtn.setBounds(590, 280, 60, 40);

        loginBtn.setFont(new java.awt.Font("Courier 10 Pitch", 1, 18)); // NOI18N
        loginBtn.setText("Login ->");
        loginBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        loginBtn.setFocusPainted(false);
        loginBtn.setFocusable(false);
        loginBtn.setRequestFocusEnabled(false);
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(loginBtn);
        loginBtn.setBounds(320, 350, 180, 50);

        pwdTxt.setBackground(new java.awt.Color(102, 255, 102));
        pwdTxt.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 24)); // NOI18N
        pwdTxt.setForeground(new java.awt.Color(102, 0, 0));
        pwdTxt.setText("enter you");
        pwdTxt.setToolTipText("enter your password");
        pwdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pwdTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdTxt.setEchoChar('*');
        pwdTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdTxtMouseClicked(evt);
            }
        });
        bodyPnl.add(pwdTxt);
        pwdTxt.setBounds(240, 280, 350, 40);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgadm.png"))); // NOI18N
        bodyPnl.add(icon);
        icon.setBounds(590, 0, 150, 160);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBack.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(backBtn);
        backBtn.setBounds(30, 30, 50, 50);

        crtBtn.setForeground(new java.awt.Color(153, 153, 255));
        crtBtn.setText("Create Account");
        crtBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        crtBtn.setVisible(false);
        bodyPnl.add(crtBtn);
        crtBtn.setBounds(430, 320, 150, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
        );

        setBounds(300, 200, 814, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
          String id = idTxt.getText();
          String pwd = new String(pwdTxt.getPassword());
        
        if(n == 1)
        {
            if( ("Admin".equals(id)) && ("Admin123".equals(pwd)))
            {
                new C_Admin().setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        }
        
        if(n == 2)
        {  
            String db_pass = new String();
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockite","root","rkgit123");
            
                pst = con.prepareStatement("select pass from users where id='"+id+"'");
                rs = pst.executeQuery();
                
                while(rs.next())
                {
                    db_pass = rs.getString("pass");
                }
                
                pst = con.prepareStatement("insert into current values('"+id+"')");
                pst.executeUpdate();
            
             } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
            if(db_pass.equals(pwd))
            {
                new D_User().setVisible(true);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Wrong Password");
            }
        }
        
        if(n == 3)
        {
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockite","root","rkgit123");
            
                pst = con.prepareStatement("insert into current values('"+id+"')");
                pst.executeUpdate();
            
             } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
            }
                new E_Guest().setVisible(true);
                this.setVisible(false);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void admBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admBtnActionPerformed
        // TODO add your handling code here:
        n = 1;
        
        icon.setVisible(true);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgadm.png")));
        
        idTxt.setText("enter your id");
        pwdTxt.setText("enter you");
        
        idLbl.setVisible(true);
        idTxt.setVisible(true);
        pwdLbl.setVisible(true);
        pwdTxt.setVisible(true);
        shwBtn.setVisible(true);
        crtBtn.setVisible(false);
    }//GEN-LAST:event_admBtnActionPerformed

    private void usrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrBtnActionPerformed
        // TODO add your handling code here:
        n = 2;
        
        icon.setVisible(true);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgusr.png"))); 
        
        idTxt.setText("enter your id");
        pwdTxt.setText("enter you");
        
        idLbl.setVisible(true);
        idTxt.setVisible(true);
        pwdLbl.setVisible(true);
        pwdTxt.setVisible(true);
        shwBtn.setVisible(true);
        crtBtn.setVisible(true);
    }//GEN-LAST:event_usrBtnActionPerformed

    private void gstBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gstBtnActionPerformed
        // TODO add your handling code here:
        n = 3;
        
        icon.setVisible(true);
        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imggst.png"))); 
        
        idTxt.setText("enter your id");
        pwdTxt.setText("enter you");
        
        idLbl.setVisible(true);
        idTxt.setVisible(true);
        pwdLbl.setVisible(false);
        pwdTxt.setVisible(false);
        shwBtn.setVisible(false);
        crtBtn.setVisible(false);
    }//GEN-LAST:event_gstBtnActionPerformed

    private void admBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admBtnFocusGained
        // TODO add your handling code here:
        admBtn.setBackground(new java.awt.Color(50, 102, 102));
    }//GEN-LAST:event_admBtnFocusGained

    private void admBtnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_admBtnFocusLost
        // TODO add your handling code here:
        gstBtn.setBackground(new java.awt.Color(0, 102, 102));
    }//GEN-LAST:event_admBtnFocusLost

    private void shwBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_shwBtnStateChanged
        // TODO add your handling code here:
        if(shwBtn.isSelected())
        {
            pwdTxt.setEchoChar((char)0);
            shwBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgHide.png")));
        }
        else
        {
            pwdTxt.setEchoChar('*');
            shwBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgShow.png")));
        }
    }//GEN-LAST:event_shwBtnStateChanged

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBackPressed.png")));
        new A_Welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBackPressed.png")));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBack.png")));
    }//GEN-LAST:event_backBtnMouseExited

    private void idTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTxtMouseClicked
        // TODO add your handling code here:
        idTxt.setText("");
    }//GEN-LAST:event_idTxtMouseClicked

    private void pwdTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdTxtMouseClicked
        // TODO add your handling code here:
        pwdTxt.setText("");
        pwdTxt.setEchoChar('*');
    }//GEN-LAST:event_pwdTxtMouseClicked

    private void shwBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shwBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shwBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(B_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(B_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(B_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(B_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new B_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bodyPnl;
    private javax.swing.JLabel crtBtn;
    private javax.swing.JButton gstBtn;
    private javax.swing.JLabel headLbl;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel pwdLbl;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JToggleButton shwBtn;
    private javax.swing.JButton usrBtn;
    // End of variables declaration//GEN-END:variables
}
