package stock;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
/**
 *
 * @author indrajteotia
 */
public class E_Guest extends javax.swing.JFrame {
   

    /**
     * Creates new form A_welcome
     */
    public E_Guest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPnl = new javax.swing.JPanel();
        headLbl = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();

        backBtn = new javax.swing.JButton();
        idLbl = new javax.swing.JLabel();
        idHolder = new javax.swing.JLabel();
        try{
            File name = new File("enter.txt");
            Scanner nameholder = new Scanner(name);
            String namevalue;
            while(nameholder.hasNextLine());
            {
                namevalue = nameholder.nextLine();
            }
            nameholder.close();
            idHolder.setText(namevalue);
        } catch(FileNotFoundException ex) {
            System.out.println("can't read");
        }

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guest Page");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(0, 51, 51));

        bodyPnl.setBackground(new java.awt.Color(0, 51, 51));
        bodyPnl.setLayout(null);

        headLbl.setFont(new java.awt.Font("Liberation Mono", 1, 36)); // NOI18N
        headLbl.setForeground(new java.awt.Color(0, 204, 204));
        headLbl.setText("Guest Page");
        bodyPnl.add(headLbl);
        headLbl.setBounds(290, 30, 210, 70);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imggst.png"))); // NOI18N
        bodyPnl.add(icon);
        icon.setBounds(590, 0, 150, 160);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBack.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(backBtn);
        backBtn.setBounds(30, 30, 50, 50);

        idLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        idLbl.setForeground(new java.awt.Color(102, 153, 255));
        idLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLbl.setText("UserID :");
        bodyPnl.add(idLbl);
        idLbl.setBounds(110, 80, 130, 40);

        idHolder.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        idHolder.setForeground(new java.awt.Color(0, 255, 153));
        idHolder.setText("User");
        bodyPnl.add(idHolder);
        idHolder.setBounds(260, 80, 140, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        setBounds(300, 200, 814, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBackPressed.png")));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBack.png")));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBackPressed.png")));
        new A_Welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(E_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(E_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(E_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(E_Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new E_Guest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bodyPnl;
    private javax.swing.JLabel headLbl;
    private javax.swing.JLabel icon;
    private javax.swing.JLabel idHolder;
    private javax.swing.JLabel idLbl;
    // End of variables declaration//GEN-END:variables
}
