/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package stock;

/**
 *
 * @author indra
 */
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;


public class F_Create extends javax.swing.JFrame {
    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form F_Create
     */
    public F_Create() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bodyPnl = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        passLbl = new javax.swing.JLabel();
        headLbl = new javax.swing.JLabel();
        mnyLbl = new javax.swing.JLabel();
        stkLbl = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        pwdTxt = new javax.swing.JPasswordField();
        shwBtn = new javax.swing.JToggleButton();
        stkTxt = new javax.swing.JTextField();
        mnyTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");
        setBackground(new java.awt.Color(0, 51, 51));

        bodyPnl.setBackground(new java.awt.Color(0, 51, 51));
        bodyPnl.setLayout(null);

        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBack.png"))); // NOI18N
        backBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backBtnMouseExited(evt);
            }
        });
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(backBtn);
        backBtn.setBounds(30, 30, 50, 50);

        passLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        passLbl.setForeground(new java.awt.Color(102, 153, 255));
        passLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passLbl.setText("Password");
        bodyPnl.add(passLbl);
        passLbl.setBounds(130, 190, 130, 40);

        headLbl.setFont(new java.awt.Font("Liberation Mono", 1, 36)); // NOI18N
        headLbl.setForeground(new java.awt.Color(0, 204, 204));
        headLbl.setText("Create Account Page");
        bodyPnl.add(headLbl);
        headLbl.setBounds(220, 30, 390, 70);

        mnyLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        mnyLbl.setForeground(new java.awt.Color(102, 153, 255));
        mnyLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        mnyLbl.setText("Money");
        bodyPnl.add(mnyLbl);
        mnyLbl.setBounds(130, 240, 130, 40);

        stkLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        stkLbl.setForeground(new java.awt.Color(102, 153, 255));
        stkLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        stkLbl.setText("Stocks");
        bodyPnl.add(stkLbl);
        stkLbl.setBounds(130, 290, 130, 40);

        idLbl.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        idLbl.setForeground(new java.awt.Color(102, 153, 255));
        idLbl.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLbl.setText("UserID");
        bodyPnl.add(idLbl);
        idLbl.setBounds(130, 140, 130, 40);

        idTxt.setBackground(new java.awt.Color(102, 255, 102));
        idTxt.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        idTxt.setForeground(new java.awt.Color(102, 0, 0));
        idTxt.setText("enter your id");
        idTxt.setToolTipText("enter your id");
        idTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        idTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                idTxtMouseClicked(evt);
            }
        });
        bodyPnl.add(idTxt);
        idTxt.setBounds(270, 140, 350, 32);

        pwdTxt.setBackground(new java.awt.Color(102, 255, 102));
        pwdTxt.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        pwdTxt.setForeground(new java.awt.Color(102, 0, 0));
        pwdTxt.setText("enter you");
        pwdTxt.setToolTipText("enter your password");
        pwdTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        pwdTxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pwdTxt.setEchoChar('*');
        pwdTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pwdTxtMouseClicked(evt);
            }
        });
        bodyPnl.add(pwdTxt);
        pwdTxt.setBounds(270, 200, 350, 30);

        shwBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgShow.png"))); // NOI18N
        shwBtn.setBorder(null);
        shwBtn.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                shwBtnStateChanged(evt);
            }
        });
        shwBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shwBtnActionPerformed(evt);
            }
        });
        bodyPnl.add(shwBtn);
        shwBtn.setBounds(620, 200, 60, 40);

        stkTxt.setBackground(new java.awt.Color(102, 255, 102));
        stkTxt.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        stkTxt.setForeground(new java.awt.Color(102, 0, 0));
        stkTxt.setText("enter your stocks");
        stkTxt.setToolTipText("enter your id");
        stkTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        stkTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stkTxtMouseClicked(evt);
            }
        });
        bodyPnl.add(stkTxt);
        stkTxt.setBounds(270, 300, 350, 32);

        mnyTxt.setBackground(new java.awt.Color(102, 255, 102));
        mnyTxt.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 18)); // NOI18N
        mnyTxt.setForeground(new java.awt.Color(102, 0, 0));
        mnyTxt.setText("enter your bank balance");
        mnyTxt.setToolTipText("enter your id");
        mnyTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        mnyTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnyTxtMouseClicked(evt);
            }
        });
        bodyPnl.add(mnyTxt);
        mnyTxt.setBounds(270, 250, 350, 32);

        jButton1.setBackground(new java.awt.Color(51, 0, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 153, 255));
        jButton1.setText("Create Account");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bodyPnl.add(jButton1);
        jButton1.setBounds(350, 360, 160, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bodyPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bodyPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
        );

        setBounds(300, 200, 814, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseEntered
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBackPressed.png")));
    }//GEN-LAST:event_backBtnMouseEntered

    private void backBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBtnMouseExited
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBack.png")));
    }//GEN-LAST:event_backBtnMouseExited

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgBackPressed.png")));
        new A_Welcome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    private void idTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_idTxtMouseClicked
        // TODO add your handling code here:
        idTxt.setText("");
    }//GEN-LAST:event_idTxtMouseClicked

    private void pwdTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pwdTxtMouseClicked
        // TODO add your handling code here:
        pwdTxt.setText("");
        pwdTxt.setEchoChar('*');
    }//GEN-LAST:event_pwdTxtMouseClicked

    private void shwBtnStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_shwBtnStateChanged
        // TODO add your handling code here:
        if(shwBtn.isSelected())
        {
            pwdTxt.setEchoChar((char)0);
            shwBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgHide.png")));
        }
        else
        {
            pwdTxt.setEchoChar('*');
            shwBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stock/imgShow.png")));
        }
    }//GEN-LAST:event_shwBtnStateChanged

    private void shwBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shwBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shwBtnActionPerformed

    private void stkTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stkTxtMouseClicked
        // TODO add your handling code here:
        stkTxt.setText("");
    }//GEN-LAST:event_stkTxtMouseClicked

    private void mnyTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnyTxtMouseClicked
        // TODO add your handling code here:
        mnyTxt.setText("");
    }//GEN-LAST:event_mnyTxtMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = idTxt.getText();
        String pass = new String(pwdTxt.getPassword());
        int amount = Integer.parseInt(mnyTxt.getText());
        int stock = Integer.parseInt(stkTxt.getText());
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/stockite","root","rkgit123");
            
            pst = con.prepareStatement("select * from current where id='"+id+"'");
            rs = pst.executeQuery();
            String db_id = new String();
            while(rs.next())
            {
                db_id = rs.getString("id");
            }
            if(db_id.equals(id))
            {
                JOptionPane.showMessageDialog(null, "User already exist", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
            {
                pst = con.prepareStatement("insert into users values('"+id+"','"+pass+"',"+amount+","+stock+")");
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Account Created", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "No Record Found", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bodyPnl;
    private javax.swing.JLabel headLbl;
    private javax.swing.JLabel idLbl;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel mnyLbl;
    private javax.swing.JTextField mnyTxt;
    private javax.swing.JLabel passLbl;
    private javax.swing.JPasswordField pwdTxt;
    private javax.swing.JToggleButton shwBtn;
    private javax.swing.JLabel stkLbl;
    private javax.swing.JTextField stkTxt;
    // End of variables declaration//GEN-END:variables
}
